############################################
# Minimal Cloud Build config to resolve
# unmarshalling error. Once this succeeds,
# we can reintroduce options gradually.
############################################

steps:
  # Sanity check: ensure no disallowed names are present in repo
  - name: 'gcr.io/cloud-builders/npm'
    id: name-check
    args: ['run', 'check:names']

  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hushng-101012042/app:${SHORT_SHA}',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hushng-101012042/app:${SHORT_SHA}'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'hushng-101012042-service',
        '--image',
        'us-central1-docker.pkg.dev/$PROJECT_ID/hushng-101012042/app:${SHORT_SHA}',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET