substitutions:
  _PROJECT_ID: genial-aspect-473616-v6                 # GCP Project ID
  _REGION: us-central1                                 # Deployment region
  _SERVICE_NAME: hushng-101012042-service              # Cloud Run service
  _IMAGE_REPO: us-central1-docker.pkg.dev/$_PROJECT_ID/hushng-101012042
  _IMAGE_NAME: app                                     # Image name within repo
  _ALLOW_UNAUTH: "false"                               # Toggle public access

steps:
  # 1. Ensure Dockerfile exists
  - name: alpine
    id: verify-dockerfile
    entrypoint: sh
    args: ['-c', 'test -f Dockerfile || { echo "Dockerfile missing"; exit 1; }']

  # 2. Build image (tag with commit SHA and latest)
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - -t
      - '${_IMAGE_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
      - -t
      - '${_IMAGE_REPO}/${_IMAGE_NAME}:latest'
      - .

  # 3. Push both tags
  - name: gcr.io/cloud-builders/docker
    id: push-sha
    args: ['push', '${_IMAGE_REPO}/${_IMAGE_NAME}:${SHORT_SHA}']
  - name: gcr.io/cloud-builders/docker
    id: push-latest
    args: ['push', '${_IMAGE_REPO}/${_IMAGE_NAME}:latest']

  # 4. Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: bash
    args:
      - -c
      - |
        if [ "${_ALLOW_UNAUTH}" = "true" ]; then AUTH_FLAG="--allow-unauthenticated"; else AUTH_FLAG="--no-allow-unauthenticated"; fi
        echo "Deploying ${_SERVICE_NAME} with image ${_IMAGE_REPO}/${_IMAGE_NAME}:${SHORT_SHA}";
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "${_IMAGE_REPO}/${_IMAGE_NAME}:${SHORT_SHA}" \
          --region "${_REGION}" \
          --platform managed \
          --quiet \
          ${AUTH_FLAG}

images:
  - '${_IMAGE_REPO}/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_IMAGE_REPO}/${_IMAGE_NAME}:latest'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 900s

tags:
  - hushng
  - nodejs
  - cloud-run