services:
  app:
    container_name: hushng-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
